<a href="https://colab.research.google.com/github/dibyanshu999/Python-libraries/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pandas library: usefu for data processing and analysis

pandas data frame:
is 2d tabular data structure  with labeled axes(rows and columns)

In [ ]:
import pandas as pd

In [ ]:
import kagglehub
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

Using Colab cache for faster access to the 'pima-indians-diabetes-database' dataset.

creating pandas data frame

In [ ]:
#importing  california data set
from sklearn.datasets import fetch_california_housing

In [ ]:
housing_dataset = fetch_california_housing()

In [ ]:
type(housing_dataset)

sklearn.utils._bunch.Bunch

In [ ]:
print(housing_dataset)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]]), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib repository.\nhttps://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33 (1997) 291-297\n'}

In [ ]:
#pandas dataframe
housing_df= pd.DataFrame(housing_dataset.data, columns = housing_dataset.feature_names)

In [ ]:
housing_df.head()

   MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [ ]:
housing_df.shape

(20640, 8)

importing data from csv file

In [ ]:
#csv file to pandas dataframe
diabetes_df=pd.read_csv('/(Copy) diabetes.csv')

In [ ]:
type(diabetes_df)

pandas.core.frame.DataFrame

In [ ]:
type(housing_df)

pandas.core.frame.DataFrame

In [ ]:
diabetes_df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
diabetes_df.shape

(768, 9)

LOADING FROM EXCEL FILE TO PANDAS DF:
pd.read_excel('file path')

dataframe to csv file

In [ ]:
housing_df.to_csv('housing.csv')

dataframe to excel:
df.to_excel('filename')

In [ ]:
import numpy as np

In [ ]:
#creating dataframe with random values
random_df=pd.DataFrame(np.random.rand(20,10))

In [ ]:
random_df.head()

          0         1         2  ...         7         8         9
0  0.529325  0.721507  0.852636  ...  0.311105  0.688242  0.642521
1  0.173814  0.775852  0.028141  ...  0.070960  0.855347  0.637150
2  0.584869  0.206761  0.992198  ...  0.742688  0.984022  0.163612
3  0.186384  0.698026  0.703157  ...  0.294601  0.666643  0.534960
4  0.021377  0.344906  0.475946  ...  0.686314  0.610384  0.450498

[5 rows x 10 columns]

Inspecting dataframe

In [ ]:
#finding no of rows and columns
housing_df.shape

(20640, 8)

In [ ]:
#first 5rows of df
housing_df.head()

   MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
0  8.3252      41.0  6.984127  ...  2.555556     37.88    -122.23
1  8.3014      21.0  6.238137  ...  2.109842     37.86    -122.22
2  7.2574      52.0  8.288136  ...  2.802260     37.85    -122.24
3  5.6431      52.0  5.817352  ...  2.547945     37.85    -122.25
4  3.8462      52.0  6.281853  ...  2.181467     37.85    -122.25

[5 rows x 8 columns]

In [ ]:
#last 5 rows
housing_df.tail()

       MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
20635  1.5603      25.0  5.045455  ...  2.560606     39.48    -121.09
20636  2.5568      18.0  6.114035  ...  3.122807     39.49    -121.21
20637  1.7000      17.0  5.205543  ...  2.325635     39.43    -121.22
20638  1.8672      18.0  5.329513  ...  2.123209     39.43    -121.32
20639  2.3886      16.0  5.254717  ...  2.616981     39.37    -121.24

[5 rows x 8 columns]

In [ ]:
#information about the datframe
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   MedInc      20640 non-null  float64
 1   HouseAge    20640 non-null  float64
 2   AveRooms    20640 non-null  float64
 3   AveBedrms   20640 non-null  float64
 4   Population  20640 non-null  float64
 5   AveOccup    20640 non-null  float64
 6   Latitude    20640 non-null  float64
 7   Longitude   20640 non-null  float64
dtypes: float64(8)
memory usage: 1.3 MB

In [ ]:
#finding the no of missing values
housing_df.isnull().sum()   #no missing values here

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
dtype: int64

In [ ]:
#counting values based on labels
diabetes_df.value_counts('Outcome')

Outcome
0    500
1    268
Name: count, dtype: int64

In [ ]:
#group the values based on the mean
diabetes_df.groupby('Outcome').mean()

         Pregnancies     Glucose  ...  DiabetesPedigreeFunction        Age
Outcome                           ...
0           3.298000  109.980000  ...                  0.429734  31.190000
1           4.865672  141.257463  ...                  0.550500  37.067164

[2 rows x 8 columns]

statistical measures

In [ ]:
#counting the no of values
housing_df.count()

MedInc        20640
HouseAge      20640
AveRooms      20640
AveBedrms     20640
Population    20640
AveOccup      20640
Latitude      20640
Longitude     20640
dtype: int64

In [ ]:
#mean value , column wise
housing_df.mean()

MedInc           3.870671
HouseAge        28.639486
AveRooms         5.429000
AveBedrms        1.096675
Population    1425.476744
AveOccup         3.070655
Latitude        35.631861
Longitude     -119.569704
dtype: float64

In [ ]:
#standard deviation column wise
housing_df.std()

MedInc           1.899822
HouseAge        12.585558
AveRooms         2.474173
AveBedrms        0.473911
Population    1132.462122
AveOccup        10.386050
Latitude         2.135952
Longitude        2.003532
dtype: float64

In [ ]:
#min value in each column
housing_df.min()

MedInc          0.499900
HouseAge        1.000000
AveRooms        0.846154
AveBedrms       0.333333
Population      3.000000
AveOccup        0.692308
Latitude       32.540000
Longitude    -124.350000
dtype: float64

In [ ]:
#maxvalue in each column
housing_df.max()

MedInc           15.000100
HouseAge         52.000000
AveRooms        141.909091
AveBedrms        34.066667
Population    35682.000000
AveOccup       1243.333333
Latitude         41.950000
Longitude      -114.310000
dtype: float64

In [ ]:
#all statistical measures
housing_df.describe()

             MedInc      HouseAge  ...      Latitude     Longitude
count  20640.000000  20640.000000  ...  20640.000000  20640.000000
mean       3.870671     28.639486  ...     35.631861   -119.569704
std        1.899822     12.585558  ...      2.135952      2.003532
min        0.499900      1.000000  ...     32.540000   -124.350000
25%        2.563400     18.000000  ...     33.930000   -121.800000
50%        3.534800     29.000000  ...     34.260000   -118.490000
75%        4.743250     37.000000  ...     37.710000   -118.010000
max       15.000100     52.000000  ...     41.950000   -114.310000

[8 rows x 8 columns]

In [ ]:
#adding a column to a dataframe
housing_df['price']=housing_dataset.target

In [ ]:
housing_df.head()

   MedInc  HouseAge  AveRooms  AveBedrms  ...  AveOccup  Latitude  Longitude  price
0  8.3252      41.0  6.984127   1.023810  ...  2.555556     37.88    -122.23  4.526
1  8.3014      21.0  6.238137   0.971880  ...  2.109842     37.86    -122.22  3.585
2  7.2574      52.0  8.288136   1.073446  ...  2.802260     37.85    -122.24  3.521
3  5.6431      52.0  5.817352   1.073059  ...  2.547945     37.85    -122.25  3.413
4  3.8462      52.0  6.281853   1.081081  ...  2.181467     37.85    -122.25  3.422

[5 rows x 9 columns]

In [ ]:
#removing a row
housing_df.drop(index=0,axis=0)   #index = 0,1,2... = row no.    axis=0 for row, axis=1 for column

       MedInc  HouseAge  AveRooms  ...  Latitude  Longitude  price
1      8.3014      21.0  6.238137  ...     37.86    -122.22  3.585
2      7.2574      52.0  8.288136  ...     37.85    -122.24  3.521
3      5.6431      52.0  5.817352  ...     37.85    -122.25  3.413
4      3.8462      52.0  6.281853  ...     37.85    -122.25  3.422
5      4.0368      52.0  4.761658  ...     37.85    -122.25  2.697
...       ...       ...       ...  ...       ...        ...    ...
20635  1.5603      25.0  5.045455  ...     39.48    -121.09  0.781
20636  2.5568      18.0  6.114035  ...     39.49    -121.21  0.771
20637  1.7000      17.0  5.205543  ...     39.43    -121.22  0.923
20638  1.8672      18.0  5.329513  ...     39.43    -121.32  0.847
20639  2.3886      16.0  5.254717  ...     39.37    -121.24  0.894

[20639 rows x 9 columns]

In [ ]:
#remove a column
housing_df.drop(columns= 'MedInc', axis=1)  #axis =0 for row , axis=1 for column

       HouseAge  AveRooms  AveBedrms  ...  Latitude  Longitude  price
0          41.0  6.984127   1.023810  ...     37.88    -122.23  4.526
1          21.0  6.238137   0.971880  ...     37.86    -122.22  3.585
2          52.0  8.288136   1.073446  ...     37.85    -122.24  3.521
3          52.0  5.817352   1.073059  ...     37.85    -122.25  3.413
4          52.0  6.281853   1.081081  ...     37.85    -122.25  3.422
...         ...       ...        ...  ...       ...        ...    ...
20635      25.0  5.045455   1.133333  ...     39.48    -121.09  0.781
20636      18.0  6.114035   1.315789  ...     39.49    -121.21  0.771
20637      17.0  5.205543   1.120092  ...     39.43    -121.22  0.923
20638      18.0  5.329513   1.171920  ...     39.43    -121.32  0.847
20639      16.0  5.254717   1.162264  ...     39.37    -121.24  0.894

[20640 rows x 8 columns]

In [ ]:
#locating a row using the index value
housing_df.iloc[2]

MedInc          7.257400
HouseAge       52.000000
AveRooms        8.288136
AveBedrms       1.073446
Population    496.000000
AveOccup        2.802260
Latitude       37.850000
Longitude    -122.240000
price           3.521000
Name: 2, dtype: float64

In [ ]:
 #locating a particular column
 print(housing_df.iloc[:,0])  #all values of first column
 print(housing_df.iloc[:,1])  #all values of second column
 print(housing_df.iloc[:,-1]) #all values of last column

0        8.3252
1        8.3014
2        7.2574
3        5.6431
4        3.8462
          ...
20635    1.5603
20636    2.5568
20637    1.7000
20638    1.8672
20639    2.3886
Name: MedInc, Length: 20640, dtype: float64
0        41.0
1        21.0
2        52.0
3        52.0
4        52.0
         ...
20635    25.0
20636    18.0
20637    17.0
20638    18.0
20639    16.0
Name: HouseAge, Length: 20640, dtype: float64
0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: price, Length: 20640, dtype: float64

Correlation:

1. positive

2.negative

In [ ]:
housing_df.corr()

              MedInc  HouseAge  AveRooms  ...  Latitude  Longitude     price
MedInc      1.000000 -0.119034  0.326895  ... -0.079809  -0.015176  0.688075
HouseAge   -0.119034  1.000000 -0.153277  ...  0.011173  -0.108197  0.105623
AveRooms    0.326895 -0.153277  1.000000  ...  0.106389  -0.027540  0.151948
AveBedrms  -0.062040 -0.077747  0.847621  ...  0.069721   0.013344 -0.046701
Population  0.004834 -0.296244 -0.072213  ... -0.108785   0.099773 -0.024650
AveOccup    0.018766  0.013191 -0.004852  ...  0.002366   0.002476 -0.023737
Latitude   -0.079809  0.011173  0.106389  ...  1.000000  -0.924664 -0.144160
Longitude  -0.015176 -0.108197 -0.027540  ... -0.924664   1.000000 -0.045967
price       0.688075  0.105623  0.151948  ... -0.144160  -0.045967  1.000000

[9 rows x 9 columns]